-- 推送记录表
CREATE TABLE IF NOT EXISTS  `push_record` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `fplxdm` varchar(10) DEFAULT NULL COMMENT '发票类型代码',
    `fpdm` varchar(20) DEFAULT NULL COMMENT '发票代码',
    `fphm` varchar(50) DEFAULT NULL COMMENT '发票号码',
    `jym` varchar(20) DEFAULT NULL COMMENT '校验码',
    `kprq` varchar(20) DEFAULT NULL COMMENT '开票日期',
    `gfmc` varchar(200) DEFAULT NULL COMMENT '购买方名称',
    `gfsh` varchar(50) DEFAULT NULL COMMENT '购买方税号',
    `gfyhzh` varchar(100) DEFAULT NULL COMMENT '购买方银行账号',
    `gfdzdh` varchar(200) DEFAULT NULL COMMENT '购买方地址电话',
    `xfmc` varchar(200) DEFAULT NULL COMMENT '销售方名称',
    `xfsh` varchar(50) DEFAULT NULL COMMENT '销售方税号',
    `xfyhzh` varchar(100) DEFAULT NULL COMMENT '销售方银行账号',
    `xfdzdh` varchar(200) DEFAULT NULL COMMENT '销售方地址电话',
    `hjje` decimal(18,2) DEFAULT NULL COMMENT '合计金额',
    `hjse` decimal(18,2) DEFAULT NULL COMMENT '合计税额',
    `jshj` decimal(18,2) DEFAULT NULL COMMENT '价税合计',
    `bz` varchar(500) DEFAULT NULL COMMENT '备注',
    `kpr` varchar(50) DEFAULT NULL COMMENT '开票人',
    `fhr` varchar(50) DEFAULT NULL COMMENT '复核人',
    `skr` varchar(50) DEFAULT NULL COMMENT '收款人',
    `mmq` varchar(200) DEFAULT NULL COMMENT '密码区',
    `jqbh` varchar(50) DEFAULT NULL COMMENT '机器编号',
    `jdhm` varchar(20) DEFAULT NULL COMMENT '校验码后6位',
    `invoice_status` varchar(10) DEFAULT '0' COMMENT '发票状态（0-正常，1-作废，2-红冲等）',
    `entry_status` varchar(10) DEFAULT '0' COMMENT '入账状态（0-未入账，1-已入账）',
    `push_status` varchar(10) DEFAULT '0' COMMENT '推送状态（0-未推送，1-推送中，2-已推送）',
    `push_success` varchar(10) DEFAULT '0' COMMENT '推送是否成功（0-失败，1-成功）',
    `push_error_msg` text COMMENT '推送错误信息',
    `push_time` datetime DEFAULT NULL COMMENT '推送时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_fpdm_fphm` (`fpdm`,`fphm`),
    KEY `idx_fplxdm` (`fplxdm`),
    KEY `idx_push_status` (`push_status`),
    KEY `idx_create_time` (`create_time`)
    ) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COMMENT='推送记录表';

